using static Bot.Translations.TranslationClasses;

namespace Bot.Translations
{
    /// <summary>
    /// Do not edit this file!
    /// </summary>
    public class English
    {
        public static _Trans Language = new _Trans
        {
            Error = new TError
            {
                Locked = "Bot has been locked to DJ/Admin only",
                QueueEmpty = "Queue is empty",
                UnknownOption = "Unknown option",
                NotAdmin = "You are not a Admin",
                BotNotInVoice = "Bot is not in a voice channel",
                UserNotInVoice = "You are not in a voice channel",
                UserNotSameVoice = "You are not in the same voice channel as the bot",
                NotDJ = "You are not a DJ/Admin",
                NoMusic = "The bot is not playing any music",
                NoAccess = "You do not have access to this command",
                NoJoinPerms = "Bot does not have permission to join the voice channel",
                NoSpeakPerms = "Bot does not have permission to speak in the voice channel",
                NoViewPerms = "Bot does not have permission to view the voice channel",
                UserSameVoice = "You are already in the same voice channel",
                OtherUser = "I am already playing music for another user",
                NoManageMessagesPerm = "You do not have permission Manage Messages",
                InvalidNumber = "Invalid number entered",
                SameNumber = "You cannot move a song to the same positionpost",
                VolMoreThan = "Volume cannot be more than 150",
                CouldNotPlay = "Could not play song",
                UnknownSong = "Could not find",
                UnknownGlobal = "Unknown global song",
                AlreadyPlaying = "Music already playing",
                AlreadyPaused = "Music already paused",
                SameVoice = "You are already in the same voice channel"
            },

            Feature = new TFeature
            {
                Loop = "Finished songs will be added to the queue and replayed again",
                Shuffle = "Choose a random song from the queue to play next",
                VoteSkip = "Vote skip the current song with 40% votes"
            },

            Main = new TMain
            {
                PlayTip = "Play or queue some music",
                StopAndClear = "Music stopped and queue cleared",
                StopAndLeave = "Music stopped, bot leaving voice",
                QueueCleared = "Music queue cleared",
                ChooseNumber = "Choose a number",
                GettingSongs = "Getting songs please wait",
                SpotifyTip = "Spotify albums and playlists will take longer to load"
            },

            Misc = new TMisc
            {
                Admin = "Admin",
                Info = "Info",
                Music = "Music",
                User = "User",
                Song = "Song",
                Locked = "Locked",
                Loop = "Loop",
                Queue = "Queue",
                Shuffle = "Shuffle",
                Stats = "Stats",
                Volume = "Volume",
                Stopped = "Stopped",
                Playing = "Playing",
                Paused = "Paused",
                ForceSkipped = "Force Skipped",
                VoteSkip = "Vote skip",
                Skipped = "Skipped",
                VoteSkipped = "Vote Skipped",
                Next = "Next",
                NextSong = "Next Song",
                MusicPaused = "Music paused",
                MusicResumed = "Music resumed"
            },

            Profile = new TProfile
            {

            },

            AdminCommands = new TAdminCommands
            {

            },

            DJ = new TDJ
            {
                LoopDisabled = "Loop disabled",
                LoopEnabled = "Loop enabled",
                ShuffleDisabled = "Shuffle disabled",
                ShuffleEnabled = "Shuffle enabled",
                LockInfo = "Lock the bot so only DJ/Admins can play, skip, pause",
                ForceClear = "Queue has been force cleared",
                ForceLeave = "Bot was forced to leave voice",
                ForceSkip = "Music has been force skipped",
                ForceStop = "Music has been force stopped",
                LockEnabled = "Bot has been locked to DJ/Admin only",
                LockDisabled = "Bot has been unlocked",
                MoveInfo = "Move songs in the queue",
                RemoveInfo = "Remove a song in the queue",
                VoteSkipInfo = "Enable vote skipping feature where only 40% or more of users are required to skip the current song",
                VoteSkipDisabled = "Vote skipping disabled",
                VoteSkipEnabled = "Vote skipping enabled",
                RemovedSong = "Removed song from queue",
                MovedSong = "Song has been moved"
            },

            Admin = new TAdmin
            {
               
            }
        };
    }
}
