using System.Collections.Generic;
using static Bot.Translations._Trans;

namespace Bot.Translations
{
    /// <summary>
    /// Do not edit this file!
    /// </summary>
    public class English
    {
        public static _Trans Language = new _Trans
        {
            Error = new TError
            {
                NoEmbedPerms = "El bot requiere del permiso \" Embed Links \"",
                AdminOnly = "No eres un administrador!",
                PlayerNotFound = "El jugador {0} no fue encontrado",
                ApiError = "Error de API",
                EnterIP = "Introduce una IP",
                InvalidIP = "Introduce una dirección IP válida!",
                Cooldown = "Tienes cooldown por 1 minuto!",
                EnableQuery = "Necesitas activar el Query en tu Servidor, revisa en (server.properties)",
                ListNoServers = "Este servidor no tiene servidores listados!",
                UnknownArg = "Argumento Desconocido.",
                TextLimit = "El texto no puede tener más de 22 letras o caracteres especiales",
                RequireAttachFiles = "El bot requiere de permisos para poner fotos!",
                UnknownWiki = "Item desconocido de la Wiki"
            },

            MainCommands = new TMainCommands
            {
                BotInfo = "Información & Estadisticas del Bot",
                Quiz = "Cuestionario de Minecraft",
                Color = "Código de Colores",
                NameHistory = "Historia de Nombres",
                UserProfile = "Perfil de Discord",
                Ping = "Pingea un Server de Minecraft",
                Version = "Versión de Minecraft información",
                Rcon = "Consola remota para tu servidor de Minecraft!",
                Achievement = "Obtén un Logro",
                Playing = "Personas jugando Minecraft",
                List = "Servidores de la Comunidad",
                Admin = "Comandos de Administración",
                Invite = "Añademe en tu Discord!"
            },

            Main = new TMain
            {
                HelpFooter = "También hay comandos ocultos ;)",
                MultiMC = "MultiMC te ayuda en forge y mods",
                PleaseWait = "Por favor, espera mientras hago PING",
                ServerAdminUse = "Un administrador deberia usar",
                StoleSkin = "Roba una skin",
                NameOnlyOne = "El miembro {0} solo tiene 1 nombre de records.",
                PlayingMinecraft = "Personas jugando Minecraft",
                Hi = "Hola",
                BotDesc = "Si tienes una duda, probleamas o quejas contactame en mi Discord!",
                First = "Primero"
            },

            Hidden = new THidden
            {
                FoundHiddenCommand = "Hehe, encontraste un comando oculto...",
                Herobrine = "Siempre te mira....",
                Notch = "Minecraft fue creado por Notch aka Markus Persson"
            },

            Wiki = new TWiki
            {
                Blocks = "Bloques",
                Unknown = "Desconocido",
                Player = "Jugador",
                Players = "Jugadores",
                Attack = "Ataque",
                Easy = "Facil",
                Hard = "Dificil",
                Health = "Vida",
                Height = "Tamaño",
                Width = "Medida"
            },

            Profile = new TProfile
            {
                Badges = "Logros",
                BadgeInfo = "Información de Logros",
                InvalidUserID = "UserID inválido",
                UnknownUser = "No se pudo encontrar a tal jugador",
                NotInServer = "Tu no estas en un servidor de minecraft",
                SetMCName = "Para poner tu cuenta de minecraft"
            },

            AdminCommands = new TAdminCommands
            {
                MCRole = "Crear un rol de minecraft para usuarios verificados",
                AutoPost = "Auto-Publicar tu server",
                AddServer = "Añadir un Servidor",
                RemoveServer = "Remueve un Servidor",
                SetPrefix = "Prefijo Customizado",
                ResetPrefix = "Remover el Prefijo Customizado"
            },

            Admin = new TAdmin
            {
                WantTranslation = "Quieres ayudar en los idiomas? Contacta a",
                ChangeLang = "Cambiar el Idioma del Bot",
                UseList = "Usa mc/list para los servidores listados",
                AddServer = "Pon un tag, ip, para agregar",
                AddServerAdded = "El servidor {0} fue agregado!",
                AddServerAlready = "Este servidor ya está agregado!",
                DelServerEnter = "Borrar un servidor con",
                DelServerNone = "Este servidor no anda en la lista",
                DelServerDeleted = "El servidor {0} fue removido!",
                PrefixReset = "Para resetear el prefijo usa mc/",
                LanguageSet = "Idioma del Bot seteado a"
            }
        };
    }
}